# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Smartfire Server
version: "1.0.0"
slug: smartfire_server
description: REST server for Proflame 2 fireplace control via YardStick One RF transmitter
url: "https://github.com/drusenko/smartfire-homeassistant"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
usb: true
ports:
  "5000/tcp": 5000
ports_description:
  "5000/tcp": "REST API port"
options: {}
schema: {}
